import { DeleteOutlined, LinkOutlined, PlusOutlined, ReloadOutlined, UserOutlined } from '@ant-design/icons'
import { Avatar, Button, Card, Col, Descriptions, Divider, Empty, Form, Input, List, Popconfirm, Row, Select, Space, Tag, Typography } from 'antd'
import { formatDate, refreshTimeRanges } from './utils'
import RefreshPanel from './RefreshPanel'
import PostsTable from './PostsTable'
import CurrentJobCard from './CurrentJobCard'

export default function ProfileWorkspace({ profiles, profile, profileUrl, setProfileUrl, onAddProfile, onOpenProfile, onDeleteProfile, onRefreshProfile, refresh, refreshItems, selectedRefreshItems, setSelectedRefreshItems, onApplyRefresh, refreshTimeRange, setRefreshTimeRange, posts, thumbnailUrls, selectedPosts, setSelectedPosts, filter, setFilter, onDownload, onRetry, onMetadata, onRetryMetadata, job, onCancelJob, busy }) {
  const refreshActive = refresh && ['queued', 'enumerating', 'pending_confirmation'].includes(refresh.status)
  return <Space orientation="vertical" size={16} className="page-stack">
    <Card className="hero-card" variant="borderless"><Row gutter={[24, 24]} align="middle"><Col flex="auto"><Space orientation="vertical" size={6}><Typography.Text className="eyebrow">PROFILE LIBRARY</Typography.Text><Typography.Title level={2} className="hero-title">主页作品管理</Typography.Title><Typography.Paragraph className="hero-copy">发现、确认、下载并维护抖音主页作品，所有状态与 Jellyfin 文件信息集中管理。</Typography.Paragraph></Space></Col><Col><Tag color="blue" icon={<UserOutlined />}>{profiles.length} 个主页</Tag></Col></Row></Card>
    <Card className="panel-card" title="添加抖音主页"><Form layout="inline" onFinish={onAddProfile} className="add-profile-form"><Form.Item className="profile-url-item"><Input size="large" prefix={<LinkOutlined />} value={profileUrl} onChange={event => setProfileUrl(event.target.value)} placeholder="https://www.douyin.com/user/..." /></Form.Item><Form.Item><Button size="large" type="primary" htmlType="submit" icon={<PlusOutlined />} loading={busy === 'add-profile'} disabled={!profileUrl}>添加主页</Button></Form.Item></Form></Card>
    <Card className="panel-card" title={<Space><span>我的主页</span><Typography.Text type="secondary">选择一个主页查看作品</Typography.Text></Space>}>{profiles.length ? <List grid={{ gutter: 12, xs: 1, sm: 2, lg: 3 }} dataSource={profiles} renderItem={item => <List.Item><Card size="small" hoverable className={`profile-tile ${profile?.id === item.id ? 'selected' : ''}`} onClick={() => onOpenProfile(item)}><Space align="start"><Avatar size={40} icon={<UserOutlined />} className="profile-avatar" /><Space orientation="vertical" size={3} className="profile-copy"><Typography.Text strong ellipsis={{ tooltip: item.display_name || item.sec_user_id }}>{item.display_name || item.sec_user_id}</Typography.Text><Typography.Text type="secondary" ellipsis={{ tooltip: item.sec_user_id }}>{item.sec_user_id}</Typography.Text><Space wrap size={[4, 4]}><Tag>作品 {item.post_count}</Tag><Tag color="success">已下载 {item.downloaded_count}</Tag>{item.failed_count > 0 && <Tag color="error">失败 {item.failed_count}</Tag>}</Space><Typography.Text type="secondary">更新于 {formatDate(item.last_refresh_at)}</Typography.Text></Space></Space></Card></List.Item>} /> : <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="还没有管理中的主页" />}</Card>
    {profile && <>
      <Card className="panel-card" title={<Space><Avatar icon={<UserOutlined />} /><Space orientation="vertical" size={1}><Typography.Title level={4} className="section-title">{profile.display_name || profile.sec_user_id}</Typography.Title><Typography.Text type="secondary" ellipsis={{ tooltip: profile.profile_url }}>{profile.profile_url}</Typography.Text></Space></Space>} extra={<Space wrap><Space orientation="vertical" size={2} className="range-control"><Typography.Text type="secondary">更新范围</Typography.Text><Select value={refreshTimeRange} onChange={setRefreshTimeRange} disabled={refreshActive} options={refreshTimeRanges.map(([value, label]) => ({ value, label }))} /></Space><Button type="primary" icon={<ReloadOutlined />} onClick={onRefreshProfile} loading={busy === 'refresh-profile'} disabled={refreshActive}>{refresh?.status === 'pending_confirmation' ? '有待确认更新' : '更新主页'}</Button><Popconfirm title="确定删除这个主页的管理记录吗？" description="不会删除已下载的视频文件。" onConfirm={onDeleteProfile}><Button danger type="text" icon={<DeleteOutlined />}>删除记录</Button></Popconfirm></Space>}><Divider className="compact-divider" /><Descriptions size="small" column={{ xs: 1, sm: 2, lg: 4 }} items={[{ key: 'name', label: '作者', children: profile.display_name || profile.sec_user_id }, { key: 'posts', label: '作品', children: profile.post_count }, { key: 'downloaded', label: '已下载', children: <Typography.Text type="success">{profile.downloaded_count}</Typography.Text> }, { key: 'updated', label: '上次更新', children: formatDate(profile.last_refresh_at) }]} /></Card>
      <RefreshPanel refresh={refresh} refreshItems={refreshItems} selectedRefreshItems={selectedRefreshItems} setSelectedRefreshItems={setSelectedRefreshItems} onApply={onApplyRefresh} loading={busy === 'apply-refresh'} />
      <Card className="panel-card posts-card" styles={{ body: { padding: 0 } }}><PostsTable posts={posts} profile={profile} thumbnailUrls={thumbnailUrls} selectedPosts={selectedPosts} setSelectedPosts={setSelectedPosts} filter={filter} setFilter={setFilter} onDownload={onDownload} onRetry={onRetry} onMetadata={onMetadata} onRetryMetadata={onRetryMetadata} busy={busy} /></Card>
      <CurrentJobCard job={job} onCancel={onCancelJob} loading={busy === 'cancel-job'} />
    </>}
  </Space>
}
